version: '3.4'

services:
  redis:
    restart: unless-stopped
    image: redis:3.2-alpine
    container_name: redis
    hostname: redis
    expose:
      - 6379
    environment:
      WORLD_TIDE_REDIS_ADDR: ${ WORLD_TIDE_REDIS_ADDR }
      WORLD_TIDE_URL: ${ WORLD_TIDE_URL }
      WORLD_TIDE_API_KEY: ${ WORLD_TIDE_API_KEY }
      WORLD_TIDE_TELEGRAM_TOKEN: ${ WORLD_TIDE_TELEGRAM_TOKEN }

  go:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    command: [ "./main" ]
    volumes:
      - ./bin:/app
    depends_on:
      - redis
