version: '3.4'

services:
  redis:
    restart: unless-stopped
    image: redis:3.2-alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  go:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    command: [ "./main" ]
    volumes:
      - ./bin:/app
    depends_on:
      - redis
