// Code generated by MockGen. DO NOT EDIT.
// Source: internal/tidesofphuket/client/worldTidesClient.go

// Package mock_client is a generated GoMock package.
package mock_client

import (
	reflect "reflect"
	client "tidesOfPhuket/internal/tidesofphuket/client"

	gomock "github.com/golang/mock/gomock"
)

// MockWorldTidesClient is a mock of WorldTidesClient interface.
type MockWorldTidesClient struct {
	ctrl     *gomock.Controller
	recorder *MockWorldTidesClientMockRecorder
}

// MockWorldTidesClientMockRecorder is the mock recorder for MockWorldTidesClient.
type MockWorldTidesClientMockRecorder struct {
	mock *MockWorldTidesClient
}

// NewMockWorldTidesClient creates a new mock instance.
func NewMockWorldTidesClient(ctrl *gomock.Controller) *MockWorldTidesClient {
	mock := &MockWorldTidesClient{ctrl: ctrl}
	mock.recorder = &MockWorldTidesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorldTidesClient) EXPECT() *MockWorldTidesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockWorldTidesClient) Get(worldTidesMethod string, queryParams map[string]string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", worldTidesMethod, queryParams)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWorldTidesClientMockRecorder) Get(worldTidesMethod, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWorldTidesClient)(nil).Get), worldTidesMethod, queryParams)
}

// GetExtremes mocks base method.
func (m *MockWorldTidesClient) GetExtremes(date, lat, lon string) (*client.TidesExtremeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExtremes", date, lat, lon)
	ret0, _ := ret[0].(*client.TidesExtremeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExtremes indicates an expected call of GetExtremes.
func (mr *MockWorldTidesClientMockRecorder) GetExtremes(date, lat, lon interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExtremes", reflect.TypeOf((*MockWorldTidesClient)(nil).GetExtremes), date, lat, lon)
}
