// Code generated by MockGen. DO NOT EDIT.
// Source: internal/redis/redis.go

// Package mock_redis is a generated GoMock package.
package mock_redis

import (
	reflect "reflect"
	client "tidesOfPhuket/internal/tidesofphuket/client"

	gomock "github.com/golang/mock/gomock"
)

// MockRedis is a mock of Redis interface.
type MockRedis struct {
	ctrl     *gomock.Controller
	recorder *MockRedisMockRecorder
}

// MockRedisMockRecorder is the mock recorder for MockRedis.
type MockRedisMockRecorder struct {
	mock *MockRedis
}

// NewMockRedis creates a new mock instance.
func NewMockRedis(ctrl *gomock.Controller) *MockRedis {
	mock := &MockRedis{ctrl: ctrl}
	mock.recorder = &MockRedisMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedis) EXPECT() *MockRedisMockRecorder {
	return m.recorder
}

// GetExtremesForToday mocks base method.
func (m *MockRedis) GetExtremesForToday(beach string) (*client.TidesExtremeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExtremesForToday", beach)
	ret0, _ := ret[0].(*client.TidesExtremeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExtremesForToday indicates an expected call of GetExtremesForToday.
func (mr *MockRedisMockRecorder) GetExtremesForToday(beach interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExtremesForToday", reflect.TypeOf((*MockRedis)(nil).GetExtremesForToday), beach)
}

// SaveTideInfo mocks base method.
func (m *MockRedis) SaveTideInfo(beach string, tidesInfo *client.TidesExtremeResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTideInfo", beach, tidesInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTideInfo indicates an expected call of SaveTideInfo.
func (mr *MockRedisMockRecorder) SaveTideInfo(beach, tidesInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTideInfo", reflect.TypeOf((*MockRedis)(nil).SaveTideInfo), beach, tidesInfo)
}
