name: CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - name: Run a multi-line script
        env:
          WORLD_TIDE_API_KEY: ${{ secrets.WORLD_TIDE_API_KEY }}
          WORLD_TIDE_URL: ${{ secrets.WORLD_TIDE_URL }}
          WORLD_TIDE_TELEGRAM_TOKEN: ${{ secrets.WORLD_TIDE_TELEGRAM_TOKEN }}
          WORLD_TIDE_REDIS_ADDR: ${{ secrets.WORLD_TIDE_REDIS_ADDR }}
          WORLD_TIDE_REDIS_PASSWORD: ${{ secrets.WORLD_TIDE_REDIS_PASSWORD}}
        run: |
          docker-compose build
          docker-compose up -d
