name: TEST

on:
  push:
    branches:
      - main
      - TI-*
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run test
        run: go test -v ./...
